//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Waarta.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Waarta.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        internal static string ChatTitle {
            get {
                return ResourceManager.GetString("ChatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video duration cannot exceed 10 seconds limit..
        /// </summary>
        internal static string ChatVideoLengthExceedMsg {
            get {
                return ResourceManager.GetString("ChatVideoLengthExceedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceeds Limit.
        /// </summary>
        internal static string ChatVideoLengthExceedTitle {
            get {
                return ResourceManager.GetString("ChatVideoLengthExceedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        internal static string ConGotoLoginBtn {
            get {
                return ResourceManager.GetString("ConGotoLoginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify your phone number..
        /// </summary>
        internal static string ConLogonInfoLabel {
            get {
                return ResourceManager.GetString("ConLogonInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find People by Name, Location, Profession etc.
        /// </summary>
        internal static string ConSearchBarPH {
            get {
                return ResourceManager.GetString("ConSearchBarPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chats.
        /// </summary>
        internal static string ConTitle {
            get {
                return ResourceManager.GetString("ConTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Person.
        /// </summary>
        internal static string CPAddtoContact {
            get {
                return ResourceManager.GetString("CPAddtoContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block Person.
        /// </summary>
        internal static string CPBlockRemove {
            get {
                return ResourceManager.GetString("CPBlockRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ☝ Cancel.
        /// </summary>
        internal static string CPCancelDownloadFileLabel {
            get {
                return ResourceManager.GetString("CPCancelDownloadFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ☝ Download.
        /// </summary>
        internal static string CPDownloadFileLabel {
            get {
                return ResourceManager.GetString("CPDownloadFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Action.
        /// </summary>
        internal static string CPNewContact {
            get {
                return ResourceManager.GetString("CPNewContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This person is not in your contact list..
        /// </summary>
        internal static string CPNewContactText {
            get {
                return ResourceManager.GetString("CPNewContactText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have blocked this person..
        /// </summary>
        internal static string CPPersonBlocked {
            get {
                return ResourceManager.GetString("CPPersonBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unblocked this person..
        /// </summary>
        internal static string CPPersonUnblocked {
            get {
                return ResourceManager.GetString("CPPersonUnblocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ☝ View.
        /// </summary>
        internal static string CPTapFileLabel {
            get {
                return ResourceManager.GetString("CPTapFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ☝ Play.
        /// </summary>
        internal static string CPTapVideoLabel {
            get {
                return ResourceManager.GetString("CPTapVideoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite.
        /// </summary>
        internal static string InviteBtn {
            get {
                return ResourceManager.GetString("InviteBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave.
        /// </summary>
        internal static string LeaveBtn {
            get {
                return ResourceManager.GetString("LeaveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either Phone or OTP not Provided..
        /// </summary>
        internal static string LPBadRequestMsg {
            get {
                return ResourceManager.GetString("LPBadRequestMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate OTP.
        /// </summary>
        internal static string LPGenerateOTPBtn {
            get {
                return ResourceManager.GetString("LPGenerateOTPBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LPLoginBtn {
            get {
                return ResourceManager.GetString("LPLoginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string LPMobileLabel {
            get {
                return ResourceManager.GetString("LPMobileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Mobile Number.
        /// </summary>
        internal static string LPMobileTxtPH {
            get {
                return ResourceManager.GetString("LPMobileTxtPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Name.
        /// </summary>
        internal static string LPNamePromptTitle {
            get {
                return ResourceManager.GetString("LPNamePromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number not registered..
        /// </summary>
        internal static string LPNotFound2Msg {
            get {
                return ResourceManager.GetString("LPNotFound2Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either OTP expired or invalid credentials. .
        /// </summary>
        internal static string LPNotFoundMsg {
            get {
                return ResourceManager.GetString("LPNotFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have sent an OTP at your registered mobile number..
        /// </summary>
        internal static string LPOTPGeneratedMsg {
            get {
                return ResourceManager.GetString("LPOTPGeneratedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP Sent.
        /// </summary>
        internal static string LPOTPGeneratedTitle {
            get {
                return ResourceManager.GetString("LPOTPGeneratedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Time Password.
        /// </summary>
        internal static string LPOTPPH {
            get {
                return ResourceManager.GetString("LPOTPPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register for Free.
        /// </summary>
        internal static string LPShowRegisterBtn {
            get {
                return ResourceManager.GetString("LPShowRegisterBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LPTitle {
            get {
                return ResourceManager.GetString("LPTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meetings.
        /// </summary>
        internal static string MeetingsTitle {
            get {
                return ResourceManager.GetString("MeetingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite Participants.
        /// </summary>
        internal static string MeetInviteOptionTitle {
            get {
                return ResourceManager.GetString("MeetInviteOptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waarta Meeting Invite.
        /// </summary>
        internal static string MeetInviteSubject {
            get {
                return ResourceManager.GetString("MeetInviteSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please join this meeting on Waarta. Go to Meetings tab on Waarta App and tap Join. 
        ///
        ///Meeting ID is {0}
        ///
        ///Or you can follow this link:
        ///
        ///https://waarta.com/m/{0}.
        /// </summary>
        internal static string MeetInviteText {
            get {
                return ResourceManager.GetString("MeetInviteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional. Meetings with no name will be deleted after 48 hours..
        /// </summary>
        internal static string MeetNameHelp {
            get {
                return ResourceManager.GetString("MeetNameHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a Meeting.
        /// </summary>
        internal static string MeetsCreateBtn {
            get {
                return ResourceManager.GetString("MeetsCreateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create meeting at present, please trying after some time..
        /// </summary>
        internal static string MeetsCreateerrorMsg {
            get {
                return ResourceManager.GetString("MeetsCreateerrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideal for status updates, discussions or future planning. Share text, photos, videos and documents. Messages shared in a meeting are not saved on your device..
        /// </summary>
        internal static string MeetsExplainLabel {
            get {
                return ResourceManager.GetString("MeetsExplainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting id is invalid..
        /// </summary>
        internal static string MeetsIdInvalidErrorMsg {
            get {
                return ResourceManager.GetString("MeetsIdInvalidErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        internal static string MeetsJoinBtn {
            get {
                return ResourceManager.GetString("MeetsJoinBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Meeting.
        /// </summary>
        internal static string MeetsJoinMeetingLabel {
            get {
                return ResourceManager.GetString("MeetsJoinMeetingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide meeting id.
        /// </summary>
        internal static string MeetsMeetingIDLabel {
            get {
                return ResourceManager.GetString("MeetsMeetingIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string MeetsNameLabel {
            get {
                return ResourceManager.GetString("MeetsNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional. Use this place to explain the purpose / agenda of the meeting in detail. .
        /// </summary>
        internal static string MeetsPurposeHelp {
            get {
                return ResourceManager.GetString("MeetsPurposeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose.
        /// </summary>
        internal static string MeetsPurposeLabel {
            get {
                return ResourceManager.GetString("MeetsPurposeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Profile Photo.
        /// </summary>
        internal static string MpmSavePhotoBtn {
            get {
                return ResourceManager.GetString("MpmSavePhotoBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional, but recommended. Use this space to describe yourself. Your interests, profession, hobbies etc. It&apos;s your space use it well..
        /// </summary>
        internal static string MppBioHelpLabel {
            get {
                return ResourceManager.GetString("MppBioHelpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this space to write about yourself..
        /// </summary>
        internal static string MppBioPH {
            get {
                return ResourceManager.GetString("MppBioPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of Birth.
        /// </summary>
        internal static string MppBirthYearLabel {
            get {
                return ResourceManager.GetString("MppBirthYearLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string MppCountryLabel {
            get {
                return ResourceManager.GetString("MppCountryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City / District / Area.
        /// </summary>
        internal static string MppDistrictLabel {
            get {
                return ResourceManager.GetString("MppDistrictLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string MppGenderLabel {
            get {
                return ResourceManager.GetString("MppGenderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Name.
        /// </summary>
        internal static string MppNamePH {
            get {
                return ResourceManager.GetString("MppNamePH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional, but recommended. Public visibility means your profile will be visible in searches. Private visibility means your profile will not be shown in searches..
        /// </summary>
        internal static string MppProfileVisibilityHelpLabel {
            get {
                return ResourceManager.GetString("MppProfileVisibilityHelpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Visible.
        /// </summary>
        internal static string MppProfileVisibilityLabel {
            get {
                return ResourceManager.GetString("MppProfileVisibilityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string MppStateLabel {
            get {
                return ResourceManager.GetString("MppStateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional. Provide a one line introduction of yourself..
        /// </summary>
        internal static string MppThoughtStatusHelpLabel {
            get {
                return ResourceManager.GetString("MppThoughtStatusHelpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Line Introduction.
        /// </summary>
        internal static string MppThoughtStatusLabel {
            get {
                return ResourceManager.GetString("MppThoughtStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Profile.
        /// </summary>
        internal static string MppTitle {
            get {
                return ResourceManager.GetString("MppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past.
        /// </summary>
        internal static string OldMeetingBtn {
            get {
                return ResourceManager.GetString("OldMeetingBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past Meetings.
        /// </summary>
        internal static string OMTitle {
            get {
                return ResourceManager.GetString("OMTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string PPTitle {
            get {
                return ResourceManager.GetString("PPTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Profile Picture.
        /// </summary>
        internal static string SetChangePicBtn {
            get {
                return ResourceManager.GetString("SetChangePicBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Photo.
        /// </summary>
        internal static string SetChoosePhotoBtn {
            get {
                return ResourceManager.GetString("SetChoosePhotoBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Profile.
        /// </summary>
        internal static string SetManageProfileBtn {
            get {
                return ResourceManager.GetString("SetManageProfileBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Photo.
        /// </summary>
        internal static string SetRemovePicBtn {
            get {
                return ResourceManager.GetString("SetRemovePicBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell a Friend.
        /// </summary>
        internal static string SetTAFBtn {
            get {
                return ResourceManager.GetString("SetTAFBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Photo.
        /// </summary>
        internal static string SetTakePicBtn {
            get {
                return ResourceManager.GetString("SetTakePicBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SetTitle {
            get {
                return ResourceManager.GetString("SetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Your Profile.
        /// </summary>
        internal static string SetViewProfileBtn {
            get {
                return ResourceManager.GetString("SetViewProfileBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Me.
        /// </summary>
        internal static string UniAboutMeLabel {
            get {
                return ResourceManager.GetString("UniAboutMeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Request.
        /// </summary>
        internal static string UniBadRequest {
            get {
                return ResourceManager.GetString("UniBadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block Person.
        /// </summary>
        internal static string UniBlockPerson {
            get {
                return ResourceManager.GetString("UniBlockPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string UniCancelDownloadBtn {
            get {
                return ResourceManager.GetString("UniCancelDownloadBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string UniCancelText {
            get {
                return ResourceManager.GetString("UniCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Video.
        /// </summary>
        internal static string UniCaptureVideoText {
            get {
                return ResourceManager.GetString("UniCaptureVideoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        internal static string UniDocText {
            get {
                return ResourceManager.GetString("UniDocText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string UniDownloadBtn {
            get {
                return ResourceManager.GetString("UniDownloadBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem.
        /// </summary>
        internal static string UniErrorMessageTitle {
            get {
                return ResourceManager.GetString("UniErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string UniNameLabel {
            get {
                return ResourceManager.GetString("UniNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete profile information. No name provided..
        /// </summary>
        internal static string UniNoNameMessage {
            get {
                return ResourceManager.GetString("UniNoNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        internal static string UniNotFound {
            get {
                return ResourceManager.GetString("UniNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string UniOfflineText {
            get {
                return ResourceManager.GetString("UniOfflineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string UniOK {
            get {
                return ResourceManager.GetString("UniOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string UniOnlineText {
            get {
                return ResourceManager.GetString("UniOnlineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string UniOptions {
            get {
                return ResourceManager.GetString("UniOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↝.
        /// </summary>
        internal static string UniPendingLabel {
            get {
                return ResourceManager.GetString("UniPendingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        internal static string UniPhotosText {
            get {
                return ResourceManager.GetString("UniPhotosText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⇅.
        /// </summary>
        internal static string UniReceivedLabel {
            get {
                return ResourceManager.GetString("UniReceivedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⇅.
        /// </summary>
        internal static string UniSeenLabel {
            get {
                return ResourceManager.GetString("UniSeenLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↑.
        /// </summary>
        internal static string UniSentLabel {
            get {
                return ResourceManager.GetString("UniSentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trouble brewing on server..
        /// </summary>
        internal static string UniServerErrorMsg {
            get {
                return ResourceManager.GetString("UniServerErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Error.
        /// </summary>
        internal static string UniServerErrorTitle {
            get {
                return ResourceManager.GetString("UniServerErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Photo.
        /// </summary>
        internal static string UniTakePhotoText {
            get {
                return ResourceManager.GetString("UniTakePhotoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unblock Person.
        /// </summary>
        internal static string UniUnblockPerson {
            get {
                return ResourceManager.GetString("UniUnblockPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to contact waarta server. Please check your internet connection..
        /// </summary>
        internal static string UniUnreachableHostExceptionMessage {
            get {
                return ResourceManager.GetString("UniUnreachableHostExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Phone.
        /// </summary>
        internal static string UniVerifyText {
            get {
                return ResourceManager.GetString("UniVerifyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        internal static string UniVideosText {
            get {
                return ResourceManager.GetString("UniVideosText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Profile.
        /// </summary>
        internal static string UniViewProfile {
            get {
                return ResourceManager.GetString("UniViewProfile", resourceCulture);
            }
        }
    }
}
