//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Waarta.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Waarta.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find People by Name, Location, Profession etc.
        /// </summary>
        internal static string ConSearchBarPH {
            get {
                return ResourceManager.GetString("ConSearchBarPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chats.
        /// </summary>
        internal static string ConTitle {
            get {
                return ResourceManager.GetString("ConTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either Phone or OTP not Provided..
        /// </summary>
        internal static string LPBadRequestMsg {
            get {
                return ResourceManager.GetString("LPBadRequestMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate OTP.
        /// </summary>
        internal static string LPGenerateOTPBtn {
            get {
                return ResourceManager.GetString("LPGenerateOTPBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LPLoginBtn {
            get {
                return ResourceManager.GetString("LPLoginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string LPMobileLabel {
            get {
                return ResourceManager.GetString("LPMobileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Mobile Number.
        /// </summary>
        internal static string LPMobileTxtPH {
            get {
                return ResourceManager.GetString("LPMobileTxtPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number not registered..
        /// </summary>
        internal static string LPNotFound2Msg {
            get {
                return ResourceManager.GetString("LPNotFound2Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either OTP expired or invalid credentials. .
        /// </summary>
        internal static string LPNotFoundMsg {
            get {
                return ResourceManager.GetString("LPNotFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have sent an OTP at your registered mobile number..
        /// </summary>
        internal static string LPOTPGeneratedMsg {
            get {
                return ResourceManager.GetString("LPOTPGeneratedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP Sent.
        /// </summary>
        internal static string LPOTPGeneratedTitle {
            get {
                return ResourceManager.GetString("LPOTPGeneratedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Time Password.
        /// </summary>
        internal static string LPOTPPH {
            get {
                return ResourceManager.GetString("LPOTPPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register for Free.
        /// </summary>
        internal static string LPShowRegisterBtn {
            get {
                return ResourceManager.GetString("LPShowRegisterBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LPTitle {
            get {
                return ResourceManager.GetString("LPTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Request.
        /// </summary>
        internal static string UniBadRequest {
            get {
                return ResourceManager.GetString("UniBadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        internal static string UniNotFound {
            get {
                return ResourceManager.GetString("UniNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string UniOfflineText {
            get {
                return ResourceManager.GetString("UniOfflineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string UniOK {
            get {
                return ResourceManager.GetString("UniOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string UniOnlineText {
            get {
                return ResourceManager.GetString("UniOnlineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trouble brewing on server..
        /// </summary>
        internal static string UniServerErrorMsg {
            get {
                return ResourceManager.GetString("UniServerErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Error.
        /// </summary>
        internal static string UniServerErrorTitle {
            get {
                return ResourceManager.GetString("UniServerErrorTitle", resourceCulture);
            }
        }
    }
}
