//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YocailApp.Resources.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YocailApp.Resources.Translations.AppRes", typeof(AppRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string ActionTxt {
            get {
                return ResourceManager.GetString("ActionTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelTxt {
            get {
                return ResourceManager.GetString("CancelTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment Deleted.
        /// </summary>
        internal static string CommentDeletedMessage {
            get {
                return ResourceManager.GetString("CommentDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment Posted.
        /// </summary>
        internal static string CommentSavedMessage {
            get {
                return ResourceManager.GetString("CommentSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Confirm!.
        /// </summary>
        internal static string ConfirmTxt {
            get {
                return ResourceManager.GetString("ConfirmTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You want to delete this?.
        /// </summary>
        internal static string DeleteConfirmTxt {
            get {
                return ResourceManager.GetString("DeleteConfirmTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteTxt {
            get {
                return ResourceManager.GetString("DeleteTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        internal static string EditProfileTxt {
            get {
                return ResourceManager.GetString("EditProfileTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditTxt {
            get {
                return ResourceManager.GetString("EditTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to process request..
        /// </summary>
        internal static string GenericServerErrorTxt {
            get {
                return ResourceManager.GetString("GenericServerErrorTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored Members.
        /// </summary>
        internal static string IgnoredMembersTxt {
            get {
                return ResourceManager.GetString("IgnoredMembersTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Member.
        /// </summary>
        internal static string IgnoreMemberTxt {
            get {
                return ResourceManager.GetString("IgnoreMemberTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less....
        /// </summary>
        internal static string LessTxt {
            get {
                return ResourceManager.GetString("LessTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginBtn {
            get {
                return ResourceManager.GetString("LoginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string LogoutTxt {
            get {
                return ResourceManager.GetString("LogoutTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More....
        /// </summary>
        internal static string MoreTxt {
            get {
                return ResourceManager.GetString("MoreTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No comment to post..
        /// </summary>
        internal static string NoCommentToPostMessage {
            get {
                return ResourceManager.GetString("NoCommentToPostMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet Conectivity..
        /// </summary>
        internal static string NoInternetMsg {
            get {
                return ResourceManager.GetString("NoInternetMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string NoTxt {
            get {
                return ResourceManager.GetString("NoTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordPh {
            get {
                return ResourceManager.GetString("PasswordPh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string ReportTxt {
            get {
                return ResourceManager.GetString("ReportTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string RequiredTxt {
            get {
                return ResourceManager.GetString("RequiredTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search People and #tag.
        /// </summary>
        internal static string SearchBarPH {
            get {
                return ResourceManager.GetString("SearchBarPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to process login request..
        /// </summary>
        internal static string UserLoginBadRequestTxt {
            get {
                return ResourceManager.GetString("UserLoginBadRequestTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string UsernamePh {
            get {
                return ResourceManager.GetString("UsernamePh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Credentials..
        /// </summary>
        internal static string UserNotFoundTxt {
            get {
                return ResourceManager.GetString("UserNotFoundTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string YesTxt {
            get {
                return ResourceManager.GetString("YesTxt", resourceCulture);
            }
        }
    }
}
